version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  test:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-test:
        filters:
            branches:
              only:
                - Ejercicios-1


jobs:
  build-and-test:  
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - test:
          command: ls -la
      - run:
          name: Run tests
          command: pytest tests.py
      