version: 2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest tests.py
          name: Test
orbs:
  python: circleci/python@1.1.0

workflows:
  main:
    jobs:
      - build:
        filters:
            branches:
              only: Ejercicios-1
